apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amrod.fullname" . }}-sqlserver-secret
  labels:
    {{- include "amrod.labels" . | nindent 4 }}
type: Opaque
data:
  sa-password: {{ .Values.sqlserver.env.SA_PASSWORD | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amrod.fullname" . }}-rabbitmq-secret
  labels:
    {{- include "amrod.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.env.RABBITMQ_DEFAULT_USER | b64enc | quote }}
  password: {{ .Values.rabbitmq.env.RABBITMQ_DEFAULT_PASS | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amrod.fullname" . }}-db-secret
  labels:
    {{- include "amrod.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: "Server={{ include \"amrod.fullname\" . }}-sqlserver;Database=OrderManagement;User Id=sa;Password={{ .Values.sqlserver.env.SA_PASSWORD }};TrustServerCertificate=True;"
